#!/usr/bin/env python3
"""
Migration script to convert authors.other_books from comma-separated string to JSON array

This script:
1. Reads all authors with other_books data
2. Attempts to intelligently parse comma-separated book titles
3. Converts to JSON array format
4. Updates the database
5. Provides rollback capability

Usage:
    python scripts/migrate_other_books_to_json.py          # Dry run (preview changes)
    python scripts/migrate_other_books_to_json.py --apply  # Apply changes
    python scripts/migrate_other_books_to_json.py --rollback backup.json  # Rollback
"""

import sqlite3
import json
import sys
import argparse
from datetime import datetime


def backup_data(db_path='data/database.db'):
    """Create backup of current other_books data"""
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    cursor.execute("SELECT id, name, other_books FROM authors WHERE other_books IS NOT NULL")
    authors = cursor.fetchall()
    conn.close()

    backup = {
        'timestamp': datetime.now().isoformat(),
        'authors': [
            {
                'id': author['id'],
                'name': author['name'],
                'other_books': author['other_books']
            }
            for author in authors
        ]
    }

    backup_file = f'backup_other_books_{datetime.now().strftime("%Y%m%d_%H%M%S")}.json'
    with open(backup_file, 'w') as f:
        json.dump(backup, f, indent=2)

    print(f"✓ Created backup: {backup_file}")
    return backup_file


def is_already_json(text):
    """Check if text is already in JSON format"""
    try:
        data = json.loads(text)
        return isinstance(data, list)
    except (json.JSONDecodeError, TypeError):
        return False


def parse_comma_separated_books(text):
    """
    Parse comma-separated book titles and convert to JSON array

    The data is generated by LLM which should avoid using commas in book titles.
    However, we use simple heuristic: if segment starts with lowercase "and", it's
    likely a subtitle/continuation.

    Examples that should be kept together:
    - "Through the Looking-Glass, and What Alice Found There"
    - "Childhood, Boyhood, Youth" (trilogy in one volume)
    """
    if not text or not text.strip():
        return []

    # Already JSON?
    if is_already_json(text):
        return json.loads(text)

    # Split by comma
    segments = [s.strip() for s in text.split(',') if s.strip()]
    books = []
    current_title = ""

    for i, segment in enumerate(segments):
        # First segment always starts a new title
        if i == 0:
            current_title = segment
            continue

        # Only join if segment starts with lowercase "and" or "or"
        # This preserves titles like "Through the Looking-Glass, and What Alice Found There"
        is_continuation = segment.lower().startswith('and ') or segment.lower().startswith('or ')

        if is_continuation:
            # Append to current title
            current_title += f", {segment}"
        else:
            # Save previous title and start new one
            if current_title:
                books.append(current_title)
            current_title = segment

    # Don't forget the last title
    if current_title:
        books.append(current_title)

    return books


def migrate_to_json(db_path='data/database.db', dry_run=True):
    """
    Migrate other_books from comma-separated to JSON

    Args:
        db_path: Path to database
        dry_run: If True, only show what would be changed
    """
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    cursor.execute("SELECT id, name, other_books FROM authors WHERE other_books IS NOT NULL")
    authors = cursor.fetchall()

    print(f"\nFound {len(authors)} authors with other_books data")
    print("=" * 80)

    changes = []
    already_json = 0

    for author in authors:
        author_id = author['id']
        author_name = author['name']
        current_books = author['other_books']

        # Check if already JSON
        if is_already_json(current_books):
            already_json += 1
            continue

        # Parse and convert
        books_list = parse_comma_separated_books(current_books)
        new_books_json = json.dumps(books_list)

        changes.append({
            'id': author_id,
            'name': author_name,
            'old': current_books,
            'new': new_books_json,
            'parsed': books_list
        })

        # Show change
        print(f"\n{author_name} (ID: {author_id})")
        print(f"  Current: {current_books}")
        print(f"  Parsed as:")
        for i, book in enumerate(books_list, 1):
            print(f"    {i}. {book}")
        print(f"  New JSON: {new_books_json}")

    print("\n" + "=" * 80)
    print(f"Summary:")
    print(f"  - Already in JSON format: {already_json}")
    print(f"  - Need conversion: {len(changes)}")

    if not dry_run and changes:
        print(f"\nApplying changes to {len(changes)} authors...")
        for change in changes:
            cursor.execute(
                "UPDATE authors SET other_books = ? WHERE id = ?",
                (change['new'], change['id'])
            )
        conn.commit()
        print("✓ Migration complete!")
    elif dry_run and changes:
        print(f"\nDRY RUN - No changes applied")
        print(f"Run with --apply to apply these changes")

    conn.close()
    return len(changes)


def rollback_from_backup(backup_file, db_path='data/database.db'):
    """Rollback to backup file"""
    with open(backup_file, 'r') as f:
        backup = json.load(f)

    print(f"Rolling back to backup from {backup['timestamp']}")

    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    for author in backup['authors']:
        cursor.execute(
            "UPDATE authors SET other_books = ? WHERE id = ?",
            (author['other_books'], author['id'])
        )

    conn.commit()
    conn.close()

    print(f"✓ Rollback complete - restored {len(backup['authors'])} authors")


def main():
    parser = argparse.ArgumentParser(description='Migrate other_books to JSON format')
    parser.add_argument('--apply', action='store_true', help='Apply changes (default is dry run)')
    parser.add_argument('--rollback', type=str, help='Rollback using backup file')
    parser.add_argument('--db', default='data/database.db', help='Database path')

    args = parser.parse_args()

    if args.rollback:
        rollback_from_backup(args.rollback, args.db)
    else:
        # Create backup before migration
        if args.apply:
            backup_file = backup_data(args.db)
            print(f"Backup saved as: {backup_file}")
            print("You can rollback with: python scripts/migrate_other_books_to_json.py --rollback {backup_file}\n")

        # Run migration
        dry_run = not args.apply
        migrate_to_json(args.db, dry_run=dry_run)


if __name__ == '__main__':
    main()
